"""Structural contract tests for the Prometheus-NS repository.

These tests are the Phase 0 gate: they pin the directory tree, the
config schema, the Makefile target list and the absence of attribution
markers. They do not import the ML stack, so the skeleton can be
verified on a fresh clone before any heavy dependency is installed.
"""

from __future__ import annotations

import re
from pathlib import Path

import pytest
import yaml

REPO_ROOT = Path(__file__).resolve().parents[1]

REQUIRED_DIRS = (
    "prometheus_ns/data",
    "prometheus_ns/model",
    "prometheus_ns/train",
    "prometheus_ns/symbolic",
    "prometheus_ns/autoloop",
    "prometheus_ns/eval",
    "scripts",
    "tests",
    "tests/fixtures",
    "artifacts/tokenizer",
    "artifacts/checkpoints",
    "data_raw",
    "data_clean",
    "data_clean/holdout",
    "triplets",
    "logs",
    "docs",
    "eval",
)

REQUIRED_FILES = (
    "config.yaml",
    "requirements.txt",
    "requirements-gpu.txt",
    ".gitignore",
    "Dockerfile",
    "README.md",
    "Makefile",
    "eval/prompts.yaml",
    "docs/gpu_migration.md",
    "prometheus_ns/__init__.py",
    "prometheus_ns/device.py",
    "prometheus_ns/data/crawler.py",
    "prometheus_ns/data/extractor.py",
    "prometheus_ns/data/cleaner.py",
    "prometheus_ns/data/quality.py",
    "prometheus_ns/data/reporter.py",
    "prometheus_ns/model/config.py",
    "prometheus_ns/model/blocks.py",
    "prometheus_ns/model/model.py",
    "prometheus_ns/model/tokenizer_train.py",
    "prometheus_ns/model/count_params.py",
    "prometheus_ns/train/dataset.py",
    "prometheus_ns/train/trainer.py",
    "prometheus_ns/train/schedules.py",
    "prometheus_ns/symbolic/extractor.py",
    "prometheus_ns/symbolic/consistency.py",
    "prometheus_ns/symbolic/generator.py",
    "prometheus_ns/autoloop/loop.py",
    "prometheus_ns/autoloop/promotion.py",
    "prometheus_ns/autoloop/diversity.py",
    "prometheus_ns/eval/perplexity.py",
    "prometheus_ns/eval/prompt_suite.py",
    "scripts/scaffold.py",
    "scripts/chat.py",
    "scripts/run_round.py",
    "scripts/freeze_holdout.py",
    "tests/conftest.py",
)

TRAIN_KEYS = (
    "lr_nano",
    "lr_small",
    "warmup_frac",
    "weight_decay",
    "grad_clip",
    "micro_batch",
    "grad_accum",
    "tokens_per_round_cpu",
    "tokens_per_round_gpu",
    "eval_every_steps",
    "use_bf16_gpu",
    "grad_checkpoint_gpu",
)

MODEL_PROFILE_KEYS = (
    "d_model",
    "n_layer",
    "n_head",
    "n_kv_head",
    "d_ff",
    "max_seq",
    "vocab",
    "tie_embeddings",
)

SYMBOLIC_KEYS = ("spacy_model", "min_confidence")
LOOP_KEYS = ("max_rounds", "human_gate_every", "min_ppl_gain", "max_diversity_drop", "holdout_sha256")
MAKEFILE_TARGETS = (
    "setup",
    "setup-gpu",
    "data",
    "tokenize",
    "train",
    "eval",
    "loop",
    "chat",
    "test",
    "lint",
    "docker-build",
    "clean",
)

# Attribution markers that must never appear in production files.
# tests/ is excluded from the scan because this very list lives here.
FORBIDDEN_MARKERS = (
    "generated by",
    "ai-generated",
    "created by glm",
    "created by claude",
    "created by gpt",
    "created by an ai",
    "powered by glm",
    "powered by claude",
    "powered by gpt",
    "co-authored-by",
    "assisted with ai",
    "as an ai",
    "openai",
    "anthropic",
    "chatgpt",
    "════",
)

SCAN_SUFFIXES = {".py", ".yaml", ".yml", ".md", ".sh"}
SCAN_FILENAMES = {"Makefile", "Dockerfile", "requirements.txt", "requirements-gpu.txt"}
EXCLUDED_DIRS = {
    ".git",
    ".venv",
    "__pycache__",
    ".pytest_cache",
    "node_modules",
    "data_raw",
    "data_clean",
    "triplets",
    "logs",
    "artifacts",
}


def _iter_scan_targets() -> list[Path]:
    """Source files only: metadata folders, binaries and caches excluded."""
    targets: list[Path] = []
    for path in REPO_ROOT.rglob("*"):
        if not path.is_file():
            continue
        rel_parts = set(path.relative_to(REPO_ROOT).parts[:-1])
        if rel_parts & EXCLUDED_DIRS:
            continue
        if "tests" in path.relative_to(REPO_ROOT).parts:
            continue
        if path.suffix in SCAN_SUFFIXES or path.name in SCAN_FILENAMES:
            targets.append(path)
    return targets


@pytest.fixture(scope="session")
def config_data() -> dict:
    with (REPO_ROOT / "config.yaml").open("r", encoding="utf-8") as fh:
        return yaml.safe_load(fh)


@pytest.mark.parametrize("rel", REQUIRED_DIRS)
def test_required_dir_exists(rel: str) -> None:
    assert (REPO_ROOT / rel).is_dir(), f"missing required directory: {rel}"


@pytest.mark.parametrize("rel", REQUIRED_FILES)
def test_required_file_exists(rel: str) -> None:
    assert (REPO_ROOT / rel).is_file(), f"missing required file: {rel}"


def test_config_loads(config_data: dict) -> None:
    assert isinstance(config_data, dict)
    for section in ("seed", "data", "clean", "tokenizer", "model", "train", "symbolic", "loop"):
        assert section in config_data, f"config missing top-level section: {section}"


def test_seed_is_integer(config_data: dict) -> None:
    assert isinstance(config_data["seed"], int)


@pytest.mark.parametrize("key", ("sources", "max_pages_per_source", "out_dir", "user_agent", "rps"))
def test_data_keys(config_data: dict, key: str) -> None:
    assert key in config_data["data"], f"config.data missing key: {key}"


@pytest.mark.parametrize(
    "key",
    ("min_doc_chars", "max_doc_chars", "minhash_perms", "minhash_jaccard", "keep_quantile"),
)
def test_clean_keys(config_data: dict, key: str) -> None:
    assert key in config_data["clean"], f"config.clean missing key: {key}"


def test_clean_sanity(config_data: dict) -> None:
    clean = config_data["clean"]
    assert 0 < clean["min_doc_chars"] < clean["max_doc_chars"]
    assert 0 < clean["keep_quantile"] <= 1
    assert clean["minhash_perms"] > 0


def test_tokenizer_vocabs(config_data: dict) -> None:
    tok = config_data["tokenizer"]
    assert tok["vocab_nano"] < tok["vocab_small"]
    assert tok["vocab_nano"] <= 65535 and tok["vocab_small"] <= 65535  # uint16 packing


@pytest.mark.parametrize("profile", ("nano", "small", "large"))
def test_model_profile_keys(config_data: dict, profile: str) -> None:
    profile_cfg = config_data["model"][profile]
    for key in MODEL_PROFILE_KEYS:
        assert key in profile_cfg, f"model.{profile} missing key: {key}"


@pytest.mark.parametrize("profile", ("nano", "small", "large"))
def test_profile_invariants(config_data: dict, profile: str) -> None:
    p = config_data["model"][profile]
    assert p["n_kv_head"] <= p["n_head"], "GQA contract: n_kv_head <= n_head"
    assert p["n_head"] % p["n_kv_head"] == 0
    assert p["d_model"] % p["n_head"] == 0
    assert p["d_ff"] > p["d_model"]
    expected_vocab = config_data["tokenizer"]["vocab_nano" if profile == "nano" else "vocab_small"]
    assert p["vocab"] == expected_vocab, f"model.{profile}.vocab must match tokenizer vocab"


def test_active_profile_is_known(config_data: dict) -> None:
    assert config_data["model"]["profile"] in ("nano", "small", "large")


@pytest.mark.parametrize("key", TRAIN_KEYS)
def test_train_keys(config_data: dict, key: str) -> None:
    assert key in config_data["train"], f"config.train missing key: {key}"


def test_device_specific_batch_sections(config_data: dict) -> None:
    for section in ("micro_batch", "grad_accum"):
        values = config_data["train"][section]
        assert "cpu" in values and "gpu" in values
        assert values["cpu"] > 0 and values["gpu"] > 0


@pytest.mark.parametrize("key", SYMBOLIC_KEYS)
def test_symbolic_keys(config_data: dict, key: str) -> None:
    assert key in config_data["symbolic"]


def test_symbolic_confidence_range(config_data: dict) -> None:
    assert 0 < config_data["symbolic"]["min_confidence"] <= 1


@pytest.mark.parametrize("key", LOOP_KEYS)
def test_loop_keys(config_data: dict, key: str) -> None:
    assert key in config_data["loop"], f"config.loop missing key: {key}"


def test_loop_sanity(config_data: dict) -> None:
    loop = config_data["loop"]
    assert 0 < loop["min_ppl_gain"] < 1
    assert 0 < loop["max_diversity_drop"] < 1
    assert loop["max_rounds"] >= 1
    assert loop["human_gate_every"] >= 1
    holdout = loop["holdout_sha256"]
    assert holdout is None or re.fullmatch(r"[0-9a-f]{64}", holdout), \
        "holdout_sha256 must be null or a lowercase sha256 hex digest"


def test_makefile_targets_declared() -> None:
    text = (REPO_ROOT / "Makefile").read_text(encoding="utf-8")
    declared = set(re.findall(r"^([a-zA-Z_-]+)\s*:", text, flags=re.MULTILINE))
    missing = [t for t in MAKEFILE_TARGETS if t not in declared]
    assert not missing, f"Makefile missing targets: {missing}"


def test_no_ai_markers() -> None:
    offenders = []
    for path in _iter_scan_targets():
        text = path.read_text(encoding="utf-8", errors="replace").lower()
        for marker in FORBIDDEN_MARKERS:
            if marker in text:
                rel = path.relative_to(REPO_ROOT)
                offenders.append(f"{rel}: contains '{marker}'")
    assert not offenders, (
        "prohibited attribution markers found:\n" + "\n".join(offenders)
    )
